### ISSUE TITLE
Uncaught (in promise) SyntaxError: Invalid or unexpected token  - simplebar-vue3

### ISSUE THREAD

**Issue by anburocky3** [teamseodo/simplebar-vue3#14]
When using simplebar-vue3, i receive this error, if i remove it, it is working as expected.

![image](https://user-images.githubusercontent.com/15264938/194553214-1ad89d25-1618-42c2-bf5d-ca2ae9c41cc0.png)

I'm using like this.

```ts
import { SimpleBar } from "simplebar-vue3";
```

```ts
<SimpleBar style="height: 400px">
 // div
</SimpleBar>
```

**Error is happening here;** 

![image](https://user-images.githubusercontent.com/15264938/194554124-d85fc9d8-c1bb-49df-9aa2-7f7679a009ad.png)

I'm using the following version.

```
 "simplebar": "^5.3.8",
 "simplebar-vue3": "^0.2.0",
  "vite": "^3.0.9",
  "vue": "^3.2.38"
```

> **Good to know that:** It is working fine in dev mode (windows), but not working in server (Linux). Please try with those to reproduce this problem.

**Comment by kadiryazici** [comment]
I think it is `simplebar`'s problem becasue I tried in production and in dev, had no errors.

**Comment by anburocky3** [comment]
> I think it is `simplebar`'s problem becasue I tried in production and in dev, had no errors.

I can make an reproduction so you can check if it is simplebar or simplebar-vue3 problem. Are you available on discord?

**Comment by kadiryazici** [comment]
Sorry cannot share discord, can you create repo with build files?

**Comment by anburocky3** [comment]
> Sorry cannot share discord, can you create repo with build files?

Oh. right, i thought it would be convenient to debug this together to make this project error-free. No problem, coming to the issue, Sadly it is a private project. But i can able to share the build files online here.

Instruction here: https://pasteio.com/x5OUqAhKkuut

**Comment by kadiryazici** [comment]
<img width="490" alt="CleanShot 2022-10-07 at 17 04 35@2x" src="https://user-images.githubusercontent.com/47540799/194572413-2f54c290-4055-471d-a8f6-bd5dde602ed2.png">

Works fine in my environment. Microsoft Edge 106 MacOS

**Comment by anburocky3** [comment]
Just do the hot-refresh, The page will get broken.

**Comment by kadiryazici** [comment]
Still couldn't find a problem :sadge:

**Comment by anburocky3** [comment]
> Still couldn't find a problem :sadge:

I even tried now, facing the same issue. Are you browsing it in Mobile? Browse it in Desktop

**Comment by kadiryazici** [comment]
Ccan you provide a gif or a video for us to look? I tried every way to see if it fails but couldn't find an issue.

**Comment by kadiryazici** [comment]
If `hot-reload` causes the issue, I don't have a way to solve it, you need to refresh manually everytime. Hot reload is a bundler thing.

**Comment by anburocky3** [comment]
Hi, it is not a `hot-reload` bug, but when i refresh the app by `CTRL + R` i see this error.

More info is provided in this video demonstration: https://youtu.be/ArteYqnjAfs

**Comment by kadiryazici** [comment]
Error occured when I tried Safari, I analized the file and it looks like the problem is `simplebar` package, not `simplebar-vue3`.

If you are using vite can you delete `node_modules/.vite` and then rebuild the page. If this does not help please create an issue in `simplebar` repo. This is just a wrapper component.
