### ISSUE TITLE
[Vue warn]: expose() should be passed a plain object, received ref. 

### ISSUE THREAD

**Issue by LaurenceJJones** [teamseodo/simplebar-vue3#15]
Hey! thank you for providing a simple vue3 wrapper. Just to let you know there is a warning from vue with your expose.

```
[Vue warn]: expose() should be passed a plain object, received ref. 
  at <SimpleBar class="overflow-x-wrap h-5/6" > 
```

https://github.com/wopehq/simplebar-vue3/blob/eb9255d70d81cb2635f34ad69081cea910df1ed8/src/Component.ts#L49

**Comment by kadiryazici** [comment]
@LaurenceJJones It was possible to expose refs before, you can use the `@created` event if `ref` does not work.

**Comment by LaurenceJJones** [comment]
Its okay I'm not using refs, just thought I inform about the warning in case others see the same warning.

**Comment by kadiryazici** [comment]
It'd be better to give the repository to owner of `simplebar` I guess. We wanted to use simplebar before and created this tiny wrapper but we don't need anymore. That way issues can be solved easily.

**Comment by fullmetalpacket** [comment]
I am also not using refs and getting this warning, is it possible to fix it?

**Comment by nestle49** [comment]
I have the same problem. What's wrong?

**Comment by LaurenceJJones** [comment]
There nothing wrong in particular. When vue3 was firstly coming up it was common to pass a ref to expose but now since vue 3 has matured they added a warning. Unless it breaks it safe to ignore for now.

**Comment by nestle49** [comment]
I change this package to native simplebar-vue package for solution
I understand that isn't error, but warning spam console too
