### ISSUE TITLE
useSimplebar return type is wrong

### ISSUE THREAD

**Issue by fk1blow** [teamseodo/simplebar-vue3#4]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
    - [ x] bug report

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
The `useSimplebar` hook definition is wrong

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
-

* **What is the expected behavior?**
the return type of the `useSimplebar` hook should be `Ref<Simplebar>` not just `Simplebar` as per https://github.com/wopehq/simplebar-vue3/blob/main/src/lib.d.ts#L26 file

* **What is the motivation / use case for changing the behavior?**
-

* **Please tell us about your environment:**
it shouldn't matter

**Comment by kadiryazici** [comment]
Thanks, I will update it soon.

**Comment by kadiryazici** [comment]
Fixed https://github.com/wopehq/simplebar-vue3/pull/5

**Comment by fk1blow** [comment]
Thanks!
